### PR TITLE
Better messages for Consent lookup and verification.

### LINKED ISSUE #3014: Loading consent for the wrong user shows 404
Loading a consent while logged in with the wrong user shows 404.

We should show that this is an invitation for a different user account, click "sign-out / sign-in" and use a user account that has the email this invitation was sent to.

Probably we should avoid leaking the email the invite was sent to.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #3014.

### CODE REVIEW

File: pkg/pub_integration/test/publisher_test.dart [hunk 1]
```diff
@@ -43,8 +43,8 @@ void main() {
           },
           body: json.encode({'granted': true}),
         );
-        if (rs1.statusCode != 404) {
-          throw Exception('Expected status code 404, got: ${rs1.statusCode}');
+        if (rs1.statusCode != 400) {
```
Comment (sigurdm) [inline pkg/pub_integration/test/publisher_test.dart]: Why not
```
expect(rs1.statusCode, 400);
```
?

File: pkg/pub_integration/test/pub_integration_test.dart [hunk 2]
```diff
@@ -42,8 +42,8 @@ void main() {
           },
           body: json.encode({'granted': true}),
         );
-        if (rs1.statusCode != 404) {
-          throw Exception('Expected status code 404, got: ${rs1.statusCode}');
+        if (rs1.statusCode != 400) {
```
Comment (sigurdm) [inline pkg/pub_integration/test/pub_integration_test.dart]: Why not

expect(rs1.statusCode, 400);
?

File: app/lib/account/consent_backend.dart [hunk 3]
```diff
@@ -187,14 +178,18 @@ class ConsentBackend {
     final c = await _db.lookupValue<Consent>(
         _db.emptyKey.append(Consent, id: consentId),
         orElse: () => null);
-    if (c == null) return null;
+    if (c == null) {
+      throw NotFoundException.resource('consent: $consentId');
```
Comment (sigurdm) [inline app/lib/account/consent_backend.dart]: Update the dartdoc of this function. It can no longer return null.

File: app/lib/account/consent_backend.dart [hunk 4]
```diff
@@ -187,14 +178,18 @@ class ConsentBackend {
...
+    }
 
     // Checking that consent is for the current user.
-    if (c.userIdOfConsent != null && c.userIdOfConsent != user.userId) {
-      return null;
+    if (c.userIdOfConsent != null) {
+      InvalidInputException.check(c.userIdOfConsent == user.userId,
+          'Consent.userId does not match current User.');
```
Comment (sigurdm) [inline app/lib/account/consent_backend.dart]: Are these strings user visible? I think they should not refer to fields in our internal representation.
What about:
`'This invitation is not for the user account currently logged in'`

File: app/lib/account/consent_backend.dart [hunk 5]
```diff
@@ -187,14 +178,18 @@ class ConsentBackend {
...
     }
-    if (c.email != null && c.email != user.email) {
-      return null;
+    if (c.email != null) {
+      InvalidInputException.check(
+          c.email == user.email, 'Consent.email does not match current User.');
```
Comment (sigurdm) [inline app/lib/account/consent_backend.dart]: What about:
`'This invitation is not for the user account currently logged in'`

File: pkg/pub_integration/test/publisher_test.dart (hunk 1 above)
Comment (isoos) [reply pkg/pub_integration/test/publisher_test.dart]: The scripts are designed for dual nature: to run as test (against the fake server), and to run as a program (against the staging or production deployment). Although only a fraction is run against the real deployment, the pattern was to use throw-like checks instead of using `package:test`. We could probably add a helper method to make that simpler.

Comment (sigurdm) [reply pkg/pub_integration/test/publisher_test.dart]: Ok - I suspected there would be a reason.
But you still import package test?

Comment (isoos) [reply pkg/pub_integration/test/publisher_test.dart]: In this case it is part of a (test-specific) callback that gets evaluated as part of the script, and should throw an exception if the consent was not valid or could not be accepted. I think we could use a `package:test` here, but I'd rather keep it consistent with the script itself.
