### PR TITLE
Try-catch session cookie processing.

### LINKED ISSUE #4111: Log and ignore errors when reading cookies and loading UserSession
If loading `UserSession` fails or reading cookie throws an error, we should log it and process the request as if it's not authenticated.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #4111.

### CODE REVIEW

File: app/lib/shared/handler_helpers.dart [hunk 1]
```diff
@@ -230,14 +230,18 @@ shelf.Handler _userSessionWrapper(shelf.Handler handler) {
...
+          request.headers[HttpHeaders.cookieHeader],
+        );
+        if (sessionId != null && sessionId.isNotEmpty) {
+          final sessionData = await accountBackend.lookupSession(sessionId);
+          if (sessionData != null) {
+            registerUserSessionData(sessionData);
+          }
         }
+      } catch (e, st) {
+        logger.warning('Unable to process session cookie.', e, st);
```
Comment (jonasfj) [inline app/lib/shared/handler_helpers.dart:244]: I think this needs to be `logger.severe` or something more than `warning`.

Afaik, warning will not trigger reporting to stack driver error reporting, only `severe` and higher, see:
https://pub.dev/documentation/appengine/latest/appengine/useLoggingPackageAdaptor.html

**Review by jonasfj — CHANGES_REQUESTED** [review]

**Review by jonasfj — APPROVED** [review]
