### PR TITLE
Run search service behind HTTP server for tests.

### LINKED ISSUE #7608: Slow tests in test/package/upload_test.dart
I was playing around with: `DEBUG=* dart test test/package/upload_test.dart` and I noticed that tests are really slow.

I reviewed the logs and found:
```
 2445 ms [frontend.search_adapter] INFO: Unable to search packages.
ERROR: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 35688, uri=http://localhost:0/search?q=is%3Aflutter-favorite&tags=-is%3Adiscontinued&tags=-is%3Aunlisted&tags=-is%3Alegacy&offset=0&limit=100, null
```

Are we forgetting to setup something, or doing some sort of retries in the start of the server.

I think this single file takes 2 min, and most of it is probably us spending 2.5s every time we start a test case :see_no_evil:

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #7608.
- Cuts down waiting for search latencies (2+ seconds in each test case).
- Needed to change the fake sign-in redirect to `/help`, as otherwise it would have populated the caches for the landing page, breaking the landing page tests.
- Removed the test using mock search service, as it doesn't add much protection, the internals of search changed and it is no longer that useful.
- Moved topPackages and youtube service initialization to a later point in the service initialization, to prevent early cache population.

### CODE REVIEW

File: app/test/frontend/handlers/landing_test.dart [hunk 1]
```diff
@@ -53,23 +51,6 @@ void main() {
       );
     });
 
-    testWithProfile('/ without a working search service', fn: () async {
```
Comment (sigurdm) [inline app/test/frontend/handlers/landing_test.dart:56]: Is this removing the fallback search entirely?

**Review by sigurdm — APPROVED** [review]

File: app/test/frontend/handlers/landing_test.dart (hunk 1 above)
Comment (isoos) [reply app/test/frontend/handlers/landing_test.dart:56]: No, we are keeping that. This test became obsolete somewhere in the past 2-3 months, where we've updated the fallback mechanism and also did the isolate-based search migration. I think this kind of mocking is not that useful in tests, as it does hide structural changes, and now, months after the actual change, it is harder to trace it back.
