### PR TITLE
Strict markdown link pruning for user-provided content.

### LINKED ISSUE #7892: Generated link in Example tab is broken
The first element in the Example tab is a generated link. This is not a content of `example/README.md`. According to my observation, there are two scenarios:

1. `pubspec.yaml` contains `repository` (usually pointing to GitHub). In this case the generated link works fine.
2. `pubspec.yaml` DOES NOT contain `repository`. In this case the generated link is broken.

I observed this behavior on many different packages.

Note: File `example/README.md` does exist and the content of this file a rendered right under the generated link.

pub-dev-example-link

### PR DESCRIPTION
**Pull request by isoos**
Fixes #7892.

### CODE REVIEW

**Comment by isoos** [comment]
Note: I've pushed this to staging for further verification.

File: app/lib/frontend/dom/dom.dart [hunk 1]
```diff
@@ -121,12 +121,24 @@ Node xAgoTimestamp(DateTime timestamp, {String? datePrefix}) {
 /// Creates a DOM node with markdown content using the default [DomContext].
 Node markdown(
   String text, {
-  bool disableHashIds = false,
+  /// When set, the markdown output is pruned more heavily than usual.
```
Comment (sigurdm) [inline app/lib/frontend/dom/dom.dart:124]: Can we list the differences?

**Review by sigurdm — APPROVED** [review]

**Review by jonasfj — APPROVED** [review]
