### PR TITLE
Lower max lookup key count for scorecard reports.

### LINKED ISSUE #4040: Could not successfully look up all keys due to resource constraints.
https://pub.dev/api/documentation/fo_components
```
api_builder: Unhandled error in API handler (incidentId: 5dff4e86-3b73-4923-8748-99fd0194885b)

Error:
    Could not successfully look up all keys due to resource constraints.

Stack:
    #0      GrpcDatastoreImpl.lookup (package:appengine/src/grpc_api_impl/datastore_impl.dart:151:9)
    <asynchronous suspension>
    #1      _lookupHelper (package:gcloud/src/db/db.dart:426:8)
    #2      DatastoreDB.lookup (package:gcloud/src/db/db.dart:338:12)
    #3      ScoreCardBackend.loadReportForAllVersions (package:pub_dev/scorecard/backend.dart:168:31)
    #4      DartdocBackend.getEntriesForVersions (package:pub_dev/dartdoc/backend.dart:187:46)
    <asynchronous suspension>
    #5      apiDocumentationHandler (package:pub_dev/frontend/handlers/custom_api.dart:51:47)
    <asynchronous suspension>
    #6      PubApi.documentation (package:pub_dev/frontend/handlers/pubapi.dart:293:7)
    #7      _$PubApiRouter.<anonymous closure> (package:pub_dev/frontend/handlers/pubapi.g.dart:389:38)
    #8      Function._apply (dart:core-patch/function_patch.dart:11:30)
    #9      Function.apply (dart:core-patch/function_patch.dart:34:12)
    #10     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:106:29)
    <asynchronous suspension>
    #11     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart)
    #12     RouterEntry.invoke (package:shelf_router/src/router_entry.dart:108:7)
    <asynchronous suspension>
    #13     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart:146:33)
    <asynchronous suspension>
    #14     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart)
    #15     Router.mount.<anonymous closure> (package:shelf_router/src/router.dart:131:21)
    #16     _Closure.call (dart:core-patch/function.dart)
    #17     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:104:30)
    <asynchronous suspension>
    #18     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart)
    #19     RouterEntry.invoke (package:shelf_router/src/router_entry.dart:108:7)
    <asynchronous suspension>
    #20     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart:146:33)
    <asynchronous suspension>
    #21     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart)
    #22     createAppHandler.<anonymous closure> (package:pub_dev/frontend/handlers.dart:60:37)
    <asynchronous suspension>
    #23     createAppHandler.<anonymous closure> (package:pub_dev/frontend/handlers.dart)
    #24     _cspHeaderWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:117:29)
    <asynchronous suspension>
    #25     _cspHeaderWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #26     _userAuthWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:213:25)
    <asynchronous suspension>
    #27     _userAuthWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #28     _requestContextWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:109:25)
    <asynchronous suspension>
    #29     _requestContextWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #30     _userSessionWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:235:38)
    <asynchronous suspension>
    #31     _userSessionWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #32     _httpsWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:257:38)
    <asynchronous suspension>
    #33     _httpsWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #34     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:192:25)
    <asynchronous suspension>
    #35     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #36     _logRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:141:27)
    <asynchronous suspension>
    #37     _logRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #38     handleRequest (package:shelf/shelf_io.dart:101:29)
    <asynchronous suspension>
    #39     runHandler.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:54:5)
    #40     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
    #41     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:58:18)
    #42     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
    #43     _rootRun (dart:async/zone.dart:1190:13)
    #44     _CustomZone.run (dart:async/zone.dart:1093:19)
    #45     _runZoned (dart:async/zone.dart:1630:10)
    #46     runZonedGuarded (dart:async/zone.dart:1618:12)
    #47     runZoned (dart:async/zone.dart:1547:12)
    #48     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #49     fork (package:gcloud/service_scope.dart:102:30)
    #50     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:56:9)
    #51     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
    #52     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #53     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #54     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #55     _rootRunUnary (dart:async/zone.dart:1198:47)
    #56     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #61     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #62     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #63     _HttpServer._handleRequest (dart:_http/http_impl.dart:2874:19)
    #64     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2629:19)
    #65     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #66     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #67     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #68     _rootRunUnary (dart:async/zone.dart:1198:47)
    #69     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #70     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #73     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #74     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #75     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #76     _HttpParser._headersEnd (dart:_http/http_parser.dart:393:19)
    #77     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
    #78     _HttpParser._parse (dart:_http/http_parser.dart:323:7)
    #79     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #80     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #81     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #82     _rootRunUnary (dart:async/zone.dart:1198:47)
    #83     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #84     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #85     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #86     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #87     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #88     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #89     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #90     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
    #91     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #92     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #93     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #94     _rootRunUnary (dart:async/zone.dart:1206:13)
    #95     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #96     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #97     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #98     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #99     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #100    _StreamController._add (dart:async/stream_controller.dart:682:7)
    #101    _StreamController.add (dart:async/stream_controller.dart:624:5)
    #102    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
    #103    _Closure.call (dart:core-patch/function.dart)
    #104    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
    #105    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #106    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #107    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #108    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes #4040.

### CODE REVIEW

**Review by jonasfj — APPROVED** [review]

File: app/lib/scorecard/backend.dart [hunk 1]
```diff
@@ -25,6 +25,13 @@ final _logger = Logger('pub.scorecard.backend');
 
 final Duration _deleteThreshold = const Duration(days: 182);
 
+/// The maximum number of keys we'll try to lookup when we need to load the
+/// scorecard or the report information for multiple versions.
+///
+/// The Datastore limit is 1000, but that caused resource constraint issues
+/// https://github.com/dart-lang/pub-dev/issues/4040
+const _batchLookupMaxKeyCount = 400;
```
Comment (jonasfj) [inline app/lib/scorecard/backend.dart:33]: I would suggest 100, since these are not empty,... The limit we're hitting is probably something like "Maximum API request size." at `10 MiB` see:
https://cloud.google.com/datastore/docs/concepts/limits

Comment (jonasfj) [reply app/lib/scorecard/backend.dart:33]: We can also make some estimate of the size of these entities..

Do they include the entire pana report?

Comment (isoos) [reply app/lib/scorecard/backend.dart]: I think that this batching utility should (eventually) live in `shared/datastore.dart` and should estimate the request size, however, I'd defer that to a later point.
