### PR TITLE
Track PackageState.finished + follow recent updates in search index.

### LINKED ISSUE #6931: Search not working properly
URL: https://pub.dev/packages?q=platform%3Awindows+fluent+ui

1) Open pub.dev and search for `fluent ui`. The `fluent_ui` package is the 7th result.

2) Check the [X] Windows Platforms filter. The `flutter_ui` package vanishes from the result.

That package has availability for Windows platform (obviously).

I checked the Windows Platform filter to be more assertive and filter out some other `fluent` widgets =\

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #6931.
- Bumped runtime version to trigger backfill.
- Tracks `updated` in both old and new search index updates.

### CODE REVIEW

File: app/lib/shared/versions.dart [hunk 1]
```diff
@@ -22,7 +22,7 @@ final RegExp runtimeVersionPattern = RegExp(r'^\d{4}\.\d{2}\.\d{2}$');
 /// when the version switch happens.
 const acceptedRuntimeVersions = <String>[
   // The current [runtimeVersion].
-  '2023.08.17',
+  '2023.08.18',
```
Comment (jonasfj) [inline app/lib/shared/versions.dart:25]: Is it safe to fallback when we've added a new property?

File: app/lib/tool/backfill/backfill_new_fields.dart [hunk 2]
```diff
@@ -12,5 +15,16 @@ final _logger = Logger('backfill_new_fields');
 /// CHANGELOG.md must be updated with the new fields, and the next
 /// release could remove the backfill from here.
 Future<void> backfillNewFields() async {
-  _logger.info('No backfill needed.');
+  _logger.info('Backfilling PackageState...');
+  final query = dbService.query<PackageState>();
```
Comment (jonasfj) [inline app/lib/tool/backfill/backfill_new_fields.dart:19]: Why not just avoid falling back to older runtime versions.

This won't fix it, new PackageState will be created when new packages are published.

And the new runtimeVersion will trigger all new PackageState entities for the next deployment we make.

File: app/lib/task/models.dart [hunk 3]
```diff
@@ -187,6 +187,10 @@ class PackageState extends db.ExpandoModel<String> {
         'dependencies: [' + (dependencies ?? []).join(', ') + ']',
       ].join('\n  ') +
       '\n)';
+
+  /// The last time the entry was updated.
```
Comment (jonasfj) [inline app/lib/task/models.dart:191]:
```suggestion
  /// The last time the entry was updated.
  ///
  /// This field is optional until runtimeVersion `2023.08.08`
  /// have been fully garbage collected.
```

**Review by jonasfj — APPROVED** [review]

File: app/lib/shared/versions.dart (hunk 1 above)
Comment (isoos) [reply app/lib/shared/versions.dart:25]: Yes, it is. (Note: this needs to be rebased and updated since we've merged the deploy PR).

File: app/lib/tool/backfill/backfill_new_fields.dart (hunk 2 above)
Comment (isoos) [reply app/lib/tool/backfill/backfill_new_fields.dart:19]: Good point, removing it.

File: app/lib/shared/versions.dart (hunk 1 above)
Comment (isoos) [reply app/lib/shared/versions.dart:25]: updated

File: app/lib/task/models.dart [hunk 4]
```diff
@@ -121,6 +121,10 @@ class PackageState extends db.ExpandoModel<String> {
   @db.DateTimeProperty(required: true)
   DateTime? lastDependencyChanged;
 
+  /// The last time the a worker completed the task with a failure or success.
```
Comment (jonasfj) [inline app/lib/task/models.dart:124]:
```suggestion
  /// The last time the a worker reported any version as completed.
```

There is no task :D

**Review by jonasfj — APPROVED** [review]
