### PR TITLE
Better pub_worker bounds: limit log size and blob index size with graceful stop conditions.

### LINKED ISSUE #9186: pub_worker should stop adding files when index approaches 10485760 bytes
The `pub_worker` should not let the index file grow too large, if it doesn't it's better to exclude a lot of files, and include the log file.

The log file is important.

```
 Error: Input stream exceeded the maxSize: 10485760
    at BucketExt.readAsBytes.<fn> (package:pub_dev/shared/storage.dart:168:11)
    at RetryOptions.retry (package:retry/retry.dart:131:16)
    at _retry (package:pub_dev/shared/storage.dart:272:10)
    at TaskBackend._readFromBucket (package:pub_dev/task/backend.dart:760:14)
    at TaskBackend._loadTaskResultIndex (package:pub_dev/task/backend.dart:820:19)
    at TaskBackend.handleUploadFinished (package:pub_dev/task/backend.dart:654:19)
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes #9186.

### CODE REVIEW

File: pkg/_pub_shared/lib/worker/limits.dart [hunk 1]
```diff
@@ -4,3 +4,6 @@
 
 /// The maximum size of the compressed blob content that we want to store and serve.
 const blobContentSizeLimit = 10 * 1024 * 1024;
+
+/// The maximum size of the blob index file.
+const blobIndexSizeLimit = blobContentSizeLimit;
```
Comment (sigurdm) [inline pkg/_pub_shared/lib/worker/limits.dart]:
```suggestion
const blobIndexSizeLimit = blobContentSizeLimit;

```
