### PR TITLE
Fix NPE when package was deleted but search still has it.

### LINKED ISSUE #2823: NPE while searching
```
Error:
    NoSuchMethodError: The getter 'name' was called on null.
    Receiver: null
    Tried calling: name

Stack:
    dart:core-patch/object_patch.dart 50:5                         Object.noSuchMethod
    package:pub_dartlang_org/package/search_service.dart 109:24    SearchService._loadResultForPackages
    package:pub_dartlang_org/package/search_service.dart 49:12     SearchService.search
    package:pub_dartlang_org/frontend/handlers/listing.dart 51:44  _packagesHandlerHtmlCore
    package:pub_dartlang_org/frontend/handlers/listing.dart 30:5   packagesHandlerHtml
    package:pub_dartlang_org/frontend/handlers/routes.dart 66:49   PubSiteService.packages
```

### PR DESCRIPTION
**Pull request by isoos**
Looks like the issue is less critical than I've first thought.
Fixes #2823.

### CODE REVIEW

File: app/lib/package/search_service.dart [hunk 1]
```diff
@@ -78,7 +78,10 @@ class SearchService {
   Future<PackageView> _getPackageView(String package) async {
```
Comment (jonasfj) [inline app/lib/package/search_service.dart]: Update doc-comment to say it can return `null`? :)
