### PR TITLE
Better Content-Type handling in API builder.

### LINKED ISSUE #6129: shelf? Invalid media type: expected quoted string.
If the header is wrong, we should reject the request 400, not have an internal error.

```
api_builder: Unhandled error in API handler (incidentId: 30468a7e-16d6-4a3c-9c64-5098048b5440)

Error:
    Error on line 1, column 27: Invalid media type: expected quoted string.
      ╷
    1 │ application/json; charset=\"utf-8\"
      │                           ^
      ╵

Stack:
    #0      wrapFormatException (package:http_parser/src/utils.dart:15:5)
    #1      new MediaType.parse (package:http_parser/src/media_type.dart:46:7)
    #2      Message._contentType (package:shelf/src/message.dart:146:42)
    #3      Message.encoding (package:shelf/src/message.dart:133:23)
    #4      Message.readAsString (package:shelf/src/message.dart:164:23)
    #5      $utilities.decodeJson (package:api_builder/api_builder.dart:90:32)
    #6      _$PubApiRouter.<anonymous closure> (package:pub_dev/frontend/handlers/pubapi.g.dart:458:28)
    #7      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:105:30)
    #8      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:111:7)
    #9      Router.call (package:shelf_router/src/router.dart:183:38)
    #10     createAppHandler.<anonymous closure> (package:pub_dev/frontend/handlers.dart:69:35)
    #11     _redirectLoopDetectorWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:74:29)
    #12     _cspHeaderWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:147:29)
    #13     _userAuthWrapper.<anonymous closure>.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:247:47)
    #14     AccountBackend.withBearerToken.<anonymous closure> (package:pub_dev/account/backend.dart:418:24)
    #15     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:205:19)
    #16     _rootRun (dart:async/zone.dart:1391:13)
    #17     _CustomZone.run (dart:async/zone.dart:1293:19)
    #18     _runZoned (dart:async/zone.dart:1829:10)
    #19     runZoned (dart:async/zone.dart:1751:10)
    #20     _ServiceScope._fork (package:gcloud/service_scope.dart:204:12)
    #21     fork (package:gcloud/service_scope.dart:102:30)
    #22     AccountBackend.withBearerToken (package:pub_dev/account/backend.dart:416:23)
    #23     _userAuthWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:246:33)
    #24     _requestContextWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:139:25)
    #25     _userSessionWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:272:38)
    #26     _httpsWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:296:38)
    #27     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:230:25)
    #28     _logRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:171:27)
    #29     handleRequest (package:shelf/shelf_io.dart:137:29)
    #30     runHandler.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:43:14)
    #31     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
    #32     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
    #33     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:205:19)
    #34     _rootRun (dart:async/zone.dart:1391:13)
    #35     _CustomZone.run (dart:async/zone.dart:1293:19)
    #36     _runZoned (dart:async/zone.dart:1829:10)
    #37     runZonedGuarded (dart:async/zone.dart:1817:12)
    #38     runZoned (dart:async/zone.dart:1748:12)
    #39     _ServiceScope._fork (package:gcloud/service_scope.dart:204:12)
    #40     fork (package:gcloud/service_scope.dart:102:30)
    #41     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:12)
    #42     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:17)
    #43     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #44     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #45     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #46     _rootRunUnary (dart:async/zone.dart:1399:47)
    #47     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
    #48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
    #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
    #52     _StreamController._add (dart:async/stream_controller.dart:648:7)
    #53     _StreamController.add (dart:async/stream_controller.dart:596:5)
    #54     _HttpServer._handleRequest (dart:_http/http_impl.dart:3303:19)
    #55     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:3053:19)
    #56     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #57     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #58     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #59     _rootRunUnary (dart:async/zone.dart:1399:47)
    #60     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
    #61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
    #62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
    #65     _StreamController._add (dart:async/stream_controller.dart:648:7)
    #66     _StreamController.add (dart:async/stream_controller.dart:596:5)
    #67     _HttpParser._headersEnd (dart:_http/http_parser.dart:403:17)
    #68     _HttpParser._doParse (dart:_http/http_parser.dart:745:15)
    #69     _HttpParser._parse (dart:_http/http_parser.dart:319:7)
    #70     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #71     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #72     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #73     _rootRunUnary (dart:async/zone.dart:1399:47)
    #74     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
    #75     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
    #76     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #77     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #78     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
    #79     _StreamController._add (dart:async/stream_controller.dart:648:7)
    #80     _StreamController.add (dart:async/stream_controller.dart:596:5)
    #81     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
    #82     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #83     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #84     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #85     _rootRunUnary (dart:async/zone.dart:1407:13)
    #86     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
    #87     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
    #88     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #89     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #90     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
    #91     _StreamController._add (dart:async/stream_controller.dart:648:7)
    #92     _StreamController.add (dart:async/stream_controller.dart:596:5)
    #93     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
    #94     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
    #95     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
    #96     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
    #97     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
    #98     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #6129.
- The `Content-Type` header is parsed to get the correct encoding when reading the body content as String. If the header has a parse issue, it throws a `FormatException`, which is now executed inside the try-catch block, handling it gracefully.
- Added logging to check if we have any non-json content type in the requests, and if we are good, we can enforce it in the next release.

### CODE REVIEW

File: pkg/api_builder/lib/api_builder.dart [hunk 1]
```diff
@@ -84,11 +84,15 @@ abstract class $utilities {
...
-    // might be sending a different Content-Type.
-    final data = await request.readAsString();
     try {
+      // TODO: Consider enforcing that requests should have 'Content-Type' set to
+      // 'application/json'. Notice that we should be careful as the CLI client,
+      // might be sending a different Content-Type.
+      if (request.mimeType != 'application/json') {
+        _log.info('Unexpected MIME type: ${request.mimeType}', request.mimeType,
+            StackTrace.current);
+      }
```
Comment (jonasfj) [inline pkg/api_builder/lib/api_builder.dart:94]: Let's file an issue to fix this. I think it's important.

**Review by jonasfj — APPROVED** [review]

File: pkg/api_builder/lib/api_builder.dart [hunk 2]
```diff
@@ -84,11 +84,15 @@ abstract class $utilities {
...
   ) async {
-    // TODO: Consider enforcing that requests should have 'Content-Type' set to
-    // 'application/json'. Notice that we should be careful as the CLI client,
-    // might be sending a different Content-Type.
-    final data = await request.readAsString();
     try {
+      // TODO: Consider enforcing that requests should have 'Content-Type' set to
+      // 'application/json'. Notice that we should be careful as the CLI client,
+      // might be sending a different Content-Type.
+      if (request.mimeType != 'application/json') {
```
Comment (jonasfj) [inline pkg/api_builder/lib/api_builder.dart:91]: You might get `application/json; charset="utf-8"` or `application/vnd.pub.v2+json`

Comment (isoos) [reply pkg/api_builder/lib/api_builder.dart]: Added `application/vnd.pub.v2+json` to the check.

**Review by jonasfj — APPROVED** [review]

File: pkg/api_builder/lib/api_builder.dart [hunk 3]
```diff
@@ -77,18 +77,27 @@ class ApiResponseException implements Exception {
           });
 }
 
+const _expectedMimeTypes = <String>{
```
Comment (jonasfj) [inline pkg/api_builder/lib/api_builder.dart:80]:
```suggestion
const _expectedJsonMimeTypes = <String>{
```
