### PR TITLE
Fix caching of Youtube API pagination + filter duplicate videoIds.

### LINKED ISSUE #8471: Package of the week section can end up with the same video twice
Happened today:
Image

### PR DESCRIPTION
**Pull request by isoos**
Fixes #8471.

### CODE REVIEW

File: app/lib/service/youtube/backend.dart [hunk 1]
```diff
@@ -121,54 +121,64 @@ class _PkgOfWeekVideoFetcher {
...
+            ));
+          } catch (e, st) {
+            // this item will be skipped, the rest of the list may be displayed
+            _logger.pubNoticeShout(
+                'youtube', 'Processing Youtube PlaylistItem failed.', e, st);
+          }
+        }
+
+        // advance to next page token
+        nextPageToken = rs.nextPageToken ?? '';
```
Comment (sigurdm) [inline app/lib/service/youtube/backend.dart:181]: Can't you just break here if `rs.nextPageToken == null` ?

File: app/lib/service/youtube/backend.dart [hunk 2]
```diff
@@ -121,54 +121,64 @@ class _PkgOfWeekVideoFetcher {
     final youtube = YouTubeApi(apiClient);
 
     try {
+      final pageTokensVisited = <String>{};
+      String nextPageToken = '';
```
[the remark this answers is not in the document]
Comment (isoos) [reply app/lib/service/youtube/backend.dart]: Updated, PTAL.

File: app/lib/service/youtube/backend.dart [hunk 3]
```diff
@@ -121,54 +121,63 @@ class _PkgOfWeekVideoFetcher {
...
+                'youtube', 'Processing Youtube PlaylistItem failed.', e, st);
+          }
+        }
+
+        pageTokensVisited.add(nextPageToken ?? '');
+        // advance to next page token
         nextPageToken = rs.nextPageToken;
-        check = nextPageToken != null && nextPageToken.isNotEmpty;
+        if (nextPageToken == null ||
+            pageTokensVisited.contains(nextPageToken)) {
```
Comment (sigurdm) [inline app/lib/service/youtube/backend.dart:178]: Can this really happen?

If so, please explain in a comment. I would expect the nextPageToken to not link us in a cycle.

**Review by sigurdm — APPROVED** [review]

File: app/lib/service/youtube/backend.dart (hunk 3 above)
Comment (isoos) [reply app/lib/service/youtube/backend.dart]: Removed. It may be a bit more defensive coding than needed.
