### PR TITLE
Retry and reduce log level on SMTP handshake timeouts.

### LINKED ISSUE #6232: Timed out while waiting for greeting -- ensure retry
If we do retry, maybe this should just be a warning..
```
Error: Timed out while waiting for greeting.

at .connect ( package:mailer/src/smtp/smtp_client.dart:127 )
at StackZoneSpecification._registerUnaryCallback.<fn> ( package:stack_trace/src/stack_zone_specification.dart:125 )
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes #6232.

### CODE REVIEW

File: app/lib/frontend/email_sender.dart [hunk 1]
```diff
@@ -157,7 +158,11 @@ class _GmailSmtpRelay implements EmailSender {
       _accessToken = null;
       throw EmailSenderException.failed();
     } on MailerException catch (e, st) {
```
Comment (jonasfj) [inline app/lib/frontend/email_sender.dart:160]: How about just doing:
```dart
} on SmtpNoGreetingException catch (e, st) {
  _logger_warning(...);
```

Printing a slightly different error message is nice too.

**Review by jonasfj — APPROVED** [review]
