### PR TITLE
Catch URL format exceptions.

### LINKED ISSUE #3068: Bad encoding in request causes 500
We have logs of requests to: `https://pub.dev/%D0%C2%BD%A8%CE%C4%BC%FE%BC%D0.zip`
These cause a 500 error response:
```
pub: Request handler failed

Error:
    FormatException: Bad UTF-8 encoding 0xc2 (at offset 2)

Stack:
    dart:convert/utf.dart 444:15                                  _Utf8Decoder.convert
    dart:convert/utf.dart 327:13                                  Utf8Decoder.convert
    dart:convert/utf.dart 59:56                                   Utf8Codec.decode
    dart:core/uri.dart 2966:21                                    _Uri._uriDecode
    dart:core/uri.dart 1160:17                                    Uri.decodeFull
    package:pub_dev/shared/handler_helpers.dart 286:24            _sanitizeRequestedUri
    package:pub_dev/shared/handler_helpers.dart 208:26            _sanitizeRequestWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 273:38            _httpsWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 141:27            _logRequestWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 109:25            _requestContextWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 229:25            _userAuthWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 251:38            _userSessionWrapper.<fn>
    package:pub_dev/shared/handler_helpers.dart 117:29            _cspHeaderWrapper.<fn>
    package:shelf/shelf_io.dart 101:29                            handleRequest
    package:pub_dev/shared/handler_helpers.dart 54:5              runHandler.<fn>
    package:appengine/appengine.dart 64:12                        runAppEngine.<fn>
    package:appengine/src/appengine_internal.dart 58:16           runAppEngine.<fn>.<fn>.<fn>
    package:gcloud/service_scope.dart 209:19                      _ServiceScope._fork.<fn>
    dart:async/zone.dart 1124:13                                  _rootRun
    dart:async/zone.dart 1021:19                                  _CustomZone.run
    dart:async/zone.dart 1516:10                                  _runZoned
    dart:async/zone.dart 1500:12                                  runZoned
    package:gcloud/service_scope.dart 208:12                      _ServiceScope._fork
    package:gcloud/service_scope.dart 104:30                      fork
    package:appengine/src/appengine_internal.dart 56:7            runAppEngine.<fn>.<fn>
    package:appengine/src/server/server.dart 77:16                AppEngineHttpServer.run.<fn>.<fn>
    package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
    package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
    dart:async/zone.dart 1132:38                                  _rootRunUnary
    dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
    dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
    dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
    dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
    dart:async/stream_controller.dart 764:19                      _SyncStreamControllerDispatch._sendData
    dart:async/stream_controller.dart 640:7                       _StreamController._add
    dart:async/stream_controller.dart 586:5                       _StreamController.add
    dart:_http/http_impl.dart 2730:19                             _HttpServer._handleRequest
    dart:_http/http_impl.dart 2488:19                             new _HttpConnection.<fn>
    package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
    package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
    dart:async/zone.dart 1132:38                                  _rootRunUnary
    dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
    dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
    dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
    dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
    dart:async/stream_controller.dart 764:19                      _SyncStreamControllerDispatch._sendData
    dart:async/stream_controller.dart 640:7                       _StreamController._add
    dart:async/stream_controller.dart 586:5                       _StreamController.add
    dart:_http/http_parser.dart 372:19                            _HttpParser._headersEnd
    dart:_http/http_parser.dart 701:15                            _HttpParser._doParse
    dart:_http/http_parser.dart 318:7                             _HttpParser._parse
    dart:_http/http_parser.dart 810:5                             _HttpParser._onData
    package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
    package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
    dart:async/zone.dart 1132:38                                  _rootRunUnary
    dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
    dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
    dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
    dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
    dart:async/stream_controller.dart 764:19                      _SyncStreamControllerDispatch._sendData
    dart:async/stream_controller.dart 640:7                       _StreamController._add
    dart:async/stream_controller.dart 586:5                       _StreamController.add
    dart:io-patch/socket_patch.dart 1829:41                       _Socket._onData
    package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
    package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
    dart:async/zone.dart 1136:13                                  _rootRunUnary
    dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
    dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
    dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
    dart:async/stream_impl.dart 263:7                             _BufferingStreamSubscription._add
    dart:async/stream_controller.dart 764:19                      _SyncStreamControllerDispatch._sendData
    dart:async/stream_controller.dart 640:7                       _StreamController._add
    dart:async/stream_controller.dart 586:5                       _StreamController.add
    dart:io-patch/socket_patch.dart 1377:33                       new _RawSocket.<fn>
    dart:io-patch/socket_patch.dart 897:14                        _NativeSocket.issueReadEvent.issue
    dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
    dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
    dart:isolate-patch/isolate_patch.dart 116:13                  _runPendingImmediateCallback
    dart:isolate-patch/isolate_patch.dart 173:5                   _RawReceivePortImpl._handleMessage
```

We should probably give a 400 bad request.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #3068

### CODE REVIEW

File: app/test/frontend/handlers/handlers_test.dart [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+import '../../shared/test_services.dart';
+
+import '_utils.dart';
+
+void main() {
+  group('bad request', () {
+    testWithServices('/%D0%C2%BD%A8%CE%C4%BC%FE%BC%D0.zip', () async {
+      final rs = await issueGet('/%D0%C2%BD%A8%CE%C4%BC%FE%BC%D0.zip');
+      expect(rs.statusCode, 404);
```
Comment (sigurdm) [inline app/test/frontend/handlers/handlers_test.dart]: I'm fine with 404 not found. Jonas suggested 400 bad request.

Comment (jonasfj) [reply app/test/frontend/handlers/handlers_test.dart]: A TODO is fine...

File: app/lib/shared/handlers.dart [hunk 2]
```diff
@@ -112,6 +112,10 @@ shelf.Response htmlResponse(String content,
   return shelf.Response(status, body: content, headers: headers);
 }
 
+// TODO: create a customized handler for invalid requests
+shelf.Response invalidRequestHandler(shelf.Request request) =>
+    notFoundHandler(request);
```
Comment (jonasfj) [inline app/lib/shared/handlers.dart]: This should ideally be a 400, because you're sending us something that's not a valid request.
