### PR TITLE
Fix NPE: modified canonicalizeVersion

### LINKED ISSUE #2474: Visiting package version that doesn't exist causes 500
Requested URL: https://pub.dev/packages/wxx_plugin/versions/0.0.1.
Request ID: e5b7945b2a3f9a090143309f00261cb3

### PR DESCRIPTION
**Pull request by isoos**
- Fixes #2474
- `canonicalizeVersion` now returns null in various failure cases, and the usual lookup afterwards also returns with null. Only the package upload needs to fail hard if the canonicalization fails.
- Also updated redirect url to version page url, removed version tab url.

### CODE REVIEW

File: app/lib/shared/utils.dart [hunk 1]
```diff
@@ -47,10 +47,19 @@ Future<T> withTempDirectory<T>(Future<T> func(Directory dir),
...
+  if (version == null || version.trim().isEmpty) {
+    return null;
+  }
   // NOTE: This is a hack because [semver.Version.parse] does not remove
   // leading zeros for integer fields.
-  final v = semver.Version.parse(version);
+  semver.Version v;
+  try {
+    v = semver.Version.parse(version);
+  } catch (_) {
```
Comment (jonasfj) [inline app/lib/shared/utils.dart]: Could we settle with catching `FormatException`, isn't that what is thrown?

It's probably fine to get an error of we're passing null or something else... Or if semver was null...
